[package]
name = "bismuth_iced"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anim = "0.1.4"
apply = "0.3.0"
iced = { version = "^0.12.0", features = ["advanced", "lazy", "svg", "tokio"] }
